export const topicsA1A2 = [
  'Aile kelimesi hakkında ne düşünüyorsunuz? Ailenin hayatımızdaki rolü.',
  'Sizin için mutluluk nedir? Mutluluğun sırrı.',
  'Nazik ve kaba insanlar hakkında ne düşünüyorsunuz?',
  'Gece yürüyüşleri.',
  'Güzel bir kahvaltı nasıl olur?',
  'Bir arkadaşta en önemli özellik nedir?',
  'Yağmurlu yaz gününün akşamı.',
  'İlk aşk ve sevgi kavramı.',
  'Sizin için özür dilemek kolay mı?',
  'Bugünlerde komşuluk. Komşularınızı tanıyor musunuz? İyi bir komşu nasıl olur?',
  'En sevdiğiniz mevsim hangisi? Neden?',
  'Güneşli bir pazar günü ne yapmak istersiniz?',
  'Evde yalnız kalmak güzel mi, sıkıcı mı?',
  'Eski fotoğraflara bakmayı sever misiniz?',
  'En sevdiğiniz şehir hangisi? Neden?',
  'Yeni insanlarla tanışmak sizin için nasıl bir tecrübe?',
  'Düğünler hakkında ne düşünüyorsunuz?',
  'Nerede yaşamak isterseniz?',
  'Hayalinizdeki küçük ev nasıl olur?',
  'Sosyal medya hakkında ne düşünüyorsunuz?',
  'Yapay Zeka hakkında ne düşünüyorsunuz?',
  'Hangi müziği dinlersiniz?',
  'Sessiz bir ev mi, kalabalık bir ev mi?',
  'Unutmak sizin için ne anlama geliyor?',
  'Geç kalır mısınız? Geç kalan insanlar hakkında genel olarak ne düşünüyorsunuz?',
  'Bisikletiniz var mı? Bisiklete binmeyi sever misiniz?',
  'Teşekkür etmek neden bu kadar önemli?',
  'Kitaplar üzerine.',
  'Filmler ve diziler üzerine.',
  'Yurtdışına taşınmak veya başka bir ülkede yaşamak ister misiniz?',
  'Araba mı? Bisiklet mi? Neden?',
  'En büyük hayaliniz nedir?',
  'Tiyatro devri bitti mi? En son ne zaman tiyatroya gittiniz?',
  'En son ne zaman doktora gittiniz? O günü anlatır mısınız?',
  'Sizce uzaylılar var mı?',
  'Hayalinizdeki odayı anlatır mısınız?',
  'Doğum gününüz ne zaman? Doğum günlerinizde ne yaparsınız?',
  'Hayalinizdeki hediye nedir?',
  'En yakın arkadaşınızı tarif edebilir misiniz?',
  'En büyük hobiniz nedir?',
  'Hiç İstanbul\'a gittiniz mi? İstanbul nasıl bir şehir?',
  'Hayalinizdeki iş nedir?',
  'Sağlığınıza dikkat ediyor musunuz?',
  'Seyahat edeceğiniz yere karar verirken nelere dikkat ediyorsunuz?',
  'Bir insan neden yabancı dilleri öğrenir?',
  'Anadiliniz hangi dillere benziyor?',
  'Kaç tane yabancı dil biliyorsunuz? Başka hangi dilleri öğrenmek istiyorsunuz?',
  'Yılın en sevdiğiniz günü nedir?',
  'Hayatınızdaki önemli günler nelerdir?',
  'Sizin ülkenizde dünyaca ünlü kişiler kimlerdir? Üçünü tarif edebilir misiniz?',
  'Neden Türkçe öğrenmek istiyorsunuz?',
  'Gazete okur musunuz?',
  'En sevdiğiniz yiyecek nedir?',
  'On yıl sonra neler yapmayı düşünüyorsunuz?',
  'Neden kimse turistlerden hoşlanmaz?',
  'Bir enstrüman çalabilir misiniz?',
];

export const topicsB1B2 = [
  'Yurtdışına taşınmak veya başka bir ülkede yaşamak ister miydiniz?',
  'Gazeteci olsaydınız ne tür haberleri yazardınız?',
  'Dünyayı daha güzel hale getirmek için neler yapabiliriz?',
  'Yoksullar için neler yapabiliriz?',
  'Daha huzurlu olmak için neler yapabiliriz?',
  'Şehrininizle ilgili bir efsane anlatır mısınız?',
  'Yerçekimi olmasaydı dünya nasıl bir yer olurdu?',
  'Hayal gücünüzü ne sıklıkta kullanırsınız?',
  'İnsanlık tarihi boyunca yaşamış olan herhangi bir kişiyle röportaj yapma şansınız olsaydı, kimi seçerdiniz?',
  'Kiralamak mı? Satın almak mı? Neden?',
  'Sizce hayvan hakları mücadelesi için yeterli bir çaba sarf ediliyor mu?',
  '21. yüzyılda insan hakları kavramından vaz mı geçtik?',
  'Ülkenizde veya yaşadığınız yerde kadın haklarına ne kadar önem veriliyor?',
  'Sizce mutluluk kavramı abartılıyor mu?',
  'Sizce uzaylılar var mı? Varlarsa, biz neden hâlâ onları bulmadık?',
  'Hayaletlere inanır mısınız?',
  'Araba kullanmayı sever misiniz? İstediğiniz arabayı seçebilme şansınız olsa hangi arabayı seçersiniz?',
  'Böceklerden korkar mısınız? Peki ya yılanlardan?',
  'Üniversiteler eskisi kadar önemli mi?',
  'Siyaseti takip ediyor musunuz? Politika ile ilgileniyor musunuz?',
  'Edebiyat hakkında ne düşünüyorsunuz? Sevdiğiniz yazar veya şair var mı?',
  'Borç para vermek hakkında ne düşünüyorsunuz? Hiç borç para verdiniz mi?',
  'Okuma alışkanlığınıza önem veriyor musunuz? Okuma alışkanlığınız var mı?',
  'Fobileriniz veya korkularınız nelerdir?',
  'En büyük hayaliniz nedir?',
  'Dünyada en çok görmek istediğiniz ülke veya yer neresidir?',
  'YouTube hayatınızda ne kadar yer alıyor? Sizce dil öğrenmekte faydalı bir araç mı?',
  'Sizce etkili bir şekilde dil öğrenmek için ne yapmalıyız?',
  '10 milyon dolarınız olsa ne yaparsınız?',
  '1 milyon dolarınız olsaydı ne yapardınız?',
  'Bilinç kavramı hakkında ne düşünüyorsunuz? Bilinçli bir insan mısınız?',
  'Sizce doğayı korumak için yeterli çaba sarf ediyor muyuz?',
  'Herkes çevre problemlerini konuşuyor, sizce konuşmanın dışında gerçekten bir şeyler yapıyor muyuz?',
  'Sizce uluslararası ölçekte yıllardır kabul gören eğitim sistemi eskidi mi?',
  'Ahlak kavramı hakkında ne düşünüyorsunuz? Ahlak ve din sizin gözünüzde aynı şey mi?',
  'Günümüzde herkes dikkat dağınıklığı probleminden muzdarip, siz de bundan şikayetçi misiniz?',
  'Evrensel bir şekilde kutsal kabul edilebilen bir şey var mıdır sizce?',
  'Sizce kural çiğnemek ne demek? Kuralları çiğneyen insanlar hakkında ne düşünüyorsunuz?',
  'En büyük ilkeniz (prensibiniz) nedir?',
  'Bazen tembellik yapıyor musunuz? Bu tür günleri yaşayan \'kendi\'nize söylemek istediğiniz bir şey var mı?',
  'Paranın bile çözmediği şeyler nelerdir?',
  'Ara sıra motivasyon eksikliği yaşıyor musunuz? Bununla nasıl başa çıkabiliriz?',
  'Bir gün uçan arabaları görecek miyiz? Onlara gerçekten ihtiyacımız var mı? Neden artık kimse onları konuşmuyor?',
  'Sizce iklim ve coğrafyanın insan karakteri üzerinde etkisi var mı?',
  'Sizce müzik, insan ruhu üzerinde etkili mi? Nasıl etkili?',
  'Marka-moda ilişkisi var mıdır? Sizce marka olan her şey kaliteli midir? Markaları takip eder misiniz? Peki ya modayı?',
  'Teknoloji düşkünü müsünüz?',
  '"Bilmemek ayıp değil; öğrenmemek ayıptır" sözünden ne anlıyorsunuz?',
];
